# Site settings
title: WebConfs - A blog about web conferences
email: coltborg@gmail.com
description: A blog about my favorite web conferences.
baseurl: '/webconfs'
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: legendofcolt
paginate: 2

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Colt Borg
      layout: "post"
      categories: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
